import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Background from "../../components/Background";
import ShaftArrow from "../../components/ShaftArrow";
import s from "./portfolio.module.scss";

export default function Alto234() {
  return (
    <>
      <Head>
        <title>Portfolio | Alto234</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Background />
      <main className={s.root}>
        <section>
          <div className={s.about}>
            <div>
              <h2 className={s.chapter}>High in the sky</h2>
              <h1 className={s.title}>Alto 234</h1>
              <p className={s.body}>
                The highest, urban bar in Africa. Found on the rooftop of The
                Leonardo in Sandton, the space boasts 360-degree views over one
                of the most-wooded cities in the world.
              </p>
            </div>
            <div style={{ width: "fit-content" }}>
              <a href="https://alto234.co.za" target="_blank">
                <button className={s.button}>Visit Site</button>
              </a>
            </div>

            <div className={s.tech}>
              <span>Tech - </span>
              <div className={s.techIcons}>
                <i className="fab fa-html5"></i>
                <i className="fab fa-css3-alt"></i>
                <i className="fab fa-js"></i>
                <i className="fab fa-bootstrap"></i>
                <img
                  src="/images/adobe.png"
                  alt="adobe coldfusion"
                  style={{ width: "20px" }}
                />
              </div>
            </div>
            <div
              style={{
                position: "absolute",
                height: "102%",
                top: 0,
                left: "-10%",
              }}
            >
              <ShaftArrow height="100%" />
            </div>
          </div>
        </section>
        <div>
          <section>
            <div className={s.extra}>
              <div>
                <p>
                  A cool and amazing site that was built on short notice with a
                  deadline in 3 days, was quite a fun project to work on and
                  finished ahead of schedule.
                  <br />
                  With complex carousals, with a weather forecast API was to
                  most complicated part of it all.
                  <br />
                  The markup had to be coded out so that the backdrop-filter
                  style could work, if you worked with it before it is quite a
                  funny thing to get working properly.
                  <br />
                  Also the cool animated button that just adding that extra WOW
                  to the site.
                  <br />
                  The site is also connected to a Adobe ColdFusion Backend.
                </p>
              </div>
              <div style={{ borderRadius: "12px", overflow: "hidden" }}>
                <Image
                  src="/images/alto-portfolio/img-01.png"
                  height={1080}
                  width={1920}
                  objectFit="contain"
                />
              </div>

              <div style={{ borderRadius: "12px", overflow: "hidden" }}>
                <Image
                  src="/images/alto-portfolio/img-02.png"
                  height={1080}
                  width={1920}
                  objectFit="contain"
                />
              </div>
              <div style={{ borderRadius: "12px", overflow: "hidden" }}>
                <Image
                  src="/images/alto-portfolio/img-03.png"
                  height={1080}
                  width={1920}
                  objectFit="contain"
                />
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
