import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Background from "../../components/Background";
import ShaftArrow from "../../components/ShaftArrow";
import s from "./portfolio.module.scss";

export default function Alto234() {
  return (
    <>
      <Head>
        <title>Portfolio | Alto234</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Background />
      <main className={s.root}>
        <section>
          <div className={s.about}>
            <div>
              <h2 className={s.chapter}>EXPERIENTIAL APPS, CAMPAIGNS & GAMES</h2>
              <h1 className={s.title}>Anti-Reality</h1>
              <p className={s.body}>
                Solve your most complex tech problems & bring your ideas to life with the power of XR.
              </p>
            </div>
            <div style={{ width: "fit-content" }}>
              <a href="https://antireality.co.za" target="_blank">
                <button className={s.button}>Visit Site</button>
              </a>
            </div>

            <div className={s.tech}>
              <span>Tech - </span>
              <div className={s.techIcons}>
                <i className="fab fa-html5"></i>
                <i className="fab fa-css3-alt"></i>
                <i className="fab fa-js"></i>
                <i className="fab fa-react"></i>
              </div>
            </div>
            <div
              style={{
                position: "absolute",
                height: "102%",
                top: 0,
                left: "-10%",
              }}
            >
              <ShaftArrow height="100%" />
            </div>
          </div>
        </section>
        <div>
          <section>
            <div className={s.extra}>
              <div>
                <p style={{textTransform: 'lowercase'}}>
                  ENGAGE YOUR AUDIENCE LIKE NEVER BEFORE, WITH EXPERIENCES THAT WILL STAY WITH THEM FOR LIFE.
                  <br />
                  THE SANBS APPROACHED US TO FIND A WAY TO RESONATE WITH THE GEN Z AND YOUNGER AUDIENCE. TRADITIONAL MARKETING DOESN'T WORK WELL ON THIS HYPER-STIMULATED, GAMING-CRAZED, DIGITALLY-ENABLED YOUNG GENERATION-SO WE KICKED IT UP A NOTCH.
                  <br />
                  IT'S 2021 YET SOME THINGS ARE A LITTLE BACKWARDS. INCLUDING THE GAMES INSDUSTRY, WITH MOST MAIN CHARACKTERS BEING WHITE MALES. SO WE SET OUT TO SHAKE THINGS UP A LITTLE, BYINTRODUCING NALEDI- ONE OF THE VERY FEW BLACK FEMALE LEAD CHARACKTERS IN THE GAMING WORLD. CATCH HER SLIDING AROUND IN HER AFROFUTURSITIC GEAR, IN THIS ADDICTIVE, SUPER-CASUAL GAME.
                  <br />
                  Also the cool animated button that just adding that extra WOW
                  to the site.
                  <br />
                  The site is also connected to a Adobe ColdFusion Backend.
                </p>
              </div>
              <div style={{ borderRadius: "12px", overflow: "hidden" }}>
                <Image
                  src="/images/Screenshot_20.png"
                  height={1080}
                  width={1920}
                  objectFit="contain"
                />
              </div>
              <div style={{ borderRadius: "12px", overflow: "hidden" }}>
                <Image
                  src="/images/Screenshot_22.png"
                  height={1080}
                  width={1920}
                  objectFit="contain"
                />
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
