import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Background from "../../components/Background";
import s from "./portfolio.module.scss";

export default function Antireality() {
  return (
    <>
      <Head>
        <title>Portfolio | Teljoy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <main className={s.root}>
        <section>
          <div className={s.about}>
            <div>
              <h2 className={s.chapter}>Credit Takealot</h2>
              <h1 className={s.title}>Teljoy</h1>
              <p className={s.body}>
                A month-to-month contract for household appliances, furniture,
                electronics. Upgrade, downgrade or cancel at any time.
              </p>
            </div>
            <div style={{width: 'fit-content'}}>
            <a href="https://www.teljoy.co.za/" target="_blank">
              <button className={s.button}>Visit Site</button>
            </a>
            </div>
            
            <div className={s.tech}>
              <span>Tech - </span>
              <div className={s.techIcons}>
                <i class="fab fa-react"></i>
                <img
                  src="/images/redux.png"
                  alt="Redux"
                  style={{ width: "20px" }}
                />
                <img
                  src="/images/material.png"
                  alt="Material UI"
                  style={{ width: "20px" }}
                />
                <img
                  src="/images/next.png"
                  alt="Next JS"
                  style={{ width: "20px" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className={s.extra}>
            <div>
              <p>
                The largest project I have been part of building using Next and
                Redux to generate pages from an api with components and the data
                from the api, generating the pages on the server-side for SEO
                reasons. A new approach in building sites where you can build
                and setup a new page from the backend with non-code solution for
                the client.
                <br />
                <br />
                Using a lot of switches based on the url, and api data.
              </p>
            </div>
            <div
              style={{
                borderRadius: "8px",
                overflow: "hidden",
                marginBottom: "2em",
              }}
            >
              <img
                src="/images/teljoy/img-01.png"
                style={{ width: "100%", margin: "0", padding: "0" }}
              />
            </div>
            <div
              style={{
                borderRadius: "8px",
                overflow: "hidden",
                marginBottom: "2em",
              }}
            >
              <img
                src="/images/teljoy/img-02.png"
                style={{ width: "100%", margin: "0", padding: "0" }}
              />
            </div>
            <div
              style={{
                borderRadius: "8px",
                overflow: "hidden",
                marginBottom: "2em",
              }}
            >
              <img
                src="/images/teljoy/img-03.png"
                style={{ width: "100%", margin: "0", padding: "0" }}
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
